// pythia-structure-ignore: the closed 62-entry component route matrix stays one auditable hand-authored manifest
export const catalogCategories = [
  "actions",
  "forms",
  "calendar",
  "selection",
  "navigation",
  "overlays",
  "disclosure",
  "feedback",
  "data-display",
  "layout",
  "semantics",
] as const;

export type CatalogCategory = (typeof catalogCategories)[number];

export const catalogProfiles = ["public", "product"] as const;

export type CatalogProfile = (typeof catalogProfiles)[number];

export type CatalogRoute = `/components/${string}`;

export interface CatalogEntry {
  readonly category: CatalogCategory;
  readonly name: string;
  readonly profiles: readonly CatalogProfile[];
  readonly route: CatalogRoute;
  readonly search: readonly string[];
}

const sharedProfiles = catalogProfiles;

export const componentCatalog = [
  {
    name: "Button",
    category: "actions",
    route: "/components/button",
    search: ["action", "loading", "primary"],
    profiles: sharedProfiles,
  },
  {
    name: "Icon button",
    category: "actions",
    route: "/components/icon-button",
    search: ["action", "icon", "label"],
    profiles: sharedProfiles,
  },
  {
    name: "Button group",
    category: "actions",
    route: "/components/button-group",
    search: ["actions", "group"],
    profiles: sharedProfiles,
  },
  {
    name: "Link button",
    category: "actions",
    route: "/components/link-button",
    search: ["action", "anchor", "link"],
    profiles: sharedProfiles,
  },
  {
    name: "Toggle",
    category: "actions",
    route: "/components/toggle",
    search: ["action", "pressed"],
    profiles: sharedProfiles,
  },
  {
    name: "Toggle group",
    category: "actions",
    route: "/components/toggle-group",
    search: ["actions", "pressed", "group"],
    profiles: sharedProfiles,
  },
  {
    name: "Input",
    category: "forms",
    route: "/components/input",
    search: ["form", "text", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Textarea",
    category: "forms",
    route: "/components/textarea",
    search: ["form", "multiline", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Label",
    category: "forms",
    route: "/components/label",
    search: ["form", "accessible", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Field",
    category: "forms",
    route: "/components/field",
    search: ["form", "description", "error"],
    profiles: sharedProfiles,
  },
  {
    name: "Input group",
    category: "forms",
    route: "/components/input-group",
    search: ["form", "prefix", "suffix"],
    profiles: sharedProfiles,
  },
  {
    name: "OTP field",
    category: "forms",
    route: "/components/otp-field",
    search: ["form", "one-time password", "code"],
    profiles: sharedProfiles,
  },
  {
    name: "Calendar",
    category: "calendar",
    route: "/components/calendar",
    search: ["date", "day picker"],
    profiles: sharedProfiles,
  },
  {
    name: "Date picker",
    category: "calendar",
    route: "/components/date-picker",
    search: ["calendar", "date", "popover"],
    profiles: sharedProfiles,
  },
  {
    name: "Checkbox",
    category: "selection",
    route: "/components/checkbox",
    search: ["selection", "checked", "indeterminate"],
    profiles: sharedProfiles,
  },
  {
    name: "Radio group",
    category: "selection",
    route: "/components/radio-group",
    search: ["selection", "single choice", "radio"],
    profiles: sharedProfiles,
  },
  {
    name: "Switch",
    category: "selection",
    route: "/components/switch",
    search: ["selection", "toggle", "checked"],
    profiles: sharedProfiles,
  },
  {
    name: "Select",
    category: "selection",
    route: "/components/select",
    search: ["selection", "listbox", "options"],
    profiles: sharedProfiles,
  },
  {
    name: "Combobox",
    category: "selection",
    route: "/components/combobox",
    search: ["selection", "autocomplete", "filter"],
    profiles: sharedProfiles,
  },
  {
    name: "Command",
    category: "selection",
    route: "/components/command",
    search: ["selection", "palette", "search"],
    profiles: sharedProfiles,
  },
  {
    name: "Tabs",
    category: "navigation",
    route: "/components/tabs",
    search: ["navigation", "panels"],
    profiles: sharedProfiles,
  },
  {
    name: "Breadcrumb",
    category: "navigation",
    route: "/components/breadcrumb",
    search: ["navigation", "hierarchy", "trail"],
    profiles: sharedProfiles,
  },
  {
    name: "Pagination",
    category: "navigation",
    route: "/components/pagination",
    search: ["navigation", "pages"],
    profiles: sharedProfiles,
  },
  {
    name: "Navigation menu",
    category: "navigation",
    route: "/components/navigation-menu",
    search: ["navigation", "menu", "links"],
    profiles: sharedProfiles,
  },
  {
    name: "Sidebar",
    category: "navigation",
    route: "/components/sidebar",
    search: ["navigation", "rail", "sections"],
    profiles: sharedProfiles,
  },
  {
    name: "Dialog",
    category: "overlays",
    route: "/components/dialog",
    search: ["overlay", "modal"],
    profiles: sharedProfiles,
  },
  {
    name: "Alert dialog",
    category: "overlays",
    route: "/components/alert-dialog",
    search: ["overlay", "confirmation", "modal"],
    profiles: sharedProfiles,
  },
  {
    name: "Drawer / sheet",
    category: "overlays",
    route: "/components/drawer-sheet",
    search: ["overlay", "drawer", "sheet"],
    profiles: sharedProfiles,
  },
  {
    name: "Popover",
    category: "overlays",
    route: "/components/popover",
    search: ["overlay", "floating"],
    profiles: sharedProfiles,
  },
  {
    name: "Tooltip",
    category: "overlays",
    route: "/components/tooltip",
    search: ["overlay", "hint"],
    profiles: sharedProfiles,
  },
  {
    name: "Preview / hover card",
    category: "overlays",
    route: "/components/preview-hover-card",
    search: ["overlay", "preview", "hover card"],
    profiles: sharedProfiles,
  },
  {
    name: "Dropdown / menu",
    category: "overlays",
    route: "/components/dropdown-menu",
    search: ["overlay", "dropdown", "menu"],
    profiles: sharedProfiles,
  },
  {
    name: "Context menu",
    category: "overlays",
    route: "/components/context-menu",
    search: ["overlay", "menu", "right click"],
    profiles: sharedProfiles,
  },
  {
    name: "Accordion",
    category: "disclosure",
    route: "/components/accordion",
    search: ["disclosure", "expand", "collapse"],
    profiles: sharedProfiles,
  },
  {
    name: "Collapsible",
    category: "disclosure",
    route: "/components/collapsible",
    search: ["disclosure", "expand", "collapse"],
    profiles: sharedProfiles,
  },
  {
    name: "Details",
    category: "disclosure",
    route: "/components/details",
    search: ["disclosure", "native", "summary"],
    profiles: sharedProfiles,
  },
  {
    name: "Alert",
    category: "feedback",
    route: "/components/alert",
    search: ["feedback", "status", "message"],
    profiles: sharedProfiles,
  },
  {
    name: "Badge",
    category: "feedback",
    route: "/components/badge",
    search: ["feedback", "status", "label"],
    profiles: sharedProfiles,
  },
  {
    name: "Progress",
    category: "feedback",
    route: "/components/progress",
    search: ["feedback", "percentage", "determinate"],
    profiles: sharedProfiles,
  },
  {
    name: "Skeleton",
    category: "feedback",
    route: "/components/skeleton",
    search: ["feedback", "loading", "placeholder"],
    profiles: sharedProfiles,
  },
  {
    name: "Activity indicator",
    category: "feedback",
    route: "/components/activity-indicator",
    search: ["feedback", "loading", "indeterminate"],
    profiles: sharedProfiles,
  },
  {
    name: "Toast",
    category: "feedback",
    route: "/components/toast",
    search: ["feedback", "notification", "queue"],
    profiles: sharedProfiles,
  },
  {
    name: "Card",
    category: "data-display",
    route: "/components/card",
    search: ["data display", "surface", "container"],
    profiles: sharedProfiles,
  },
  {
    name: "Table",
    category: "data-display",
    route: "/components/table",
    search: ["data display", "rows", "columns"],
    profiles: sharedProfiles,
  },
  {
    name: "Avatar",
    category: "data-display",
    route: "/components/avatar",
    search: ["data display", "image", "fallback"],
    profiles: sharedProfiles,
  },
  {
    name: "Scroll area",
    category: "data-display",
    route: "/components/scroll-area",
    search: ["data display", "scrollbar", "overflow"],
    profiles: sharedProfiles,
  },
  {
    name: "Separator",
    category: "data-display",
    route: "/components/separator",
    search: ["data display", "divider"],
    profiles: sharedProfiles,
  },
  {
    name: "Empty state",
    category: "data-display",
    route: "/components/empty-state",
    search: ["data display", "empty", "no results"],
    profiles: sharedProfiles,
  },
  {
    name: "Container",
    category: "layout",
    route: "/components/container",
    search: ["layout", "measure", "width"],
    profiles: sharedProfiles,
  },
  {
    name: "Stack",
    category: "layout",
    route: "/components/stack",
    search: ["layout", "vertical", "gap"],
    profiles: sharedProfiles,
  },
  {
    name: "Inline",
    category: "layout",
    route: "/components/inline",
    search: ["layout", "horizontal", "gap"],
    profiles: sharedProfiles,
  },
  {
    name: "Resizable panels",
    category: "layout",
    route: "/components/resizable-panels",
    search: ["layout", "panels", "resize"],
    profiles: sharedProfiles,
  },
  {
    name: "Citation",
    category: "semantics",
    route: "/components/citation",
    search: ["semantics", "source", "citation"],
    profiles: sharedProfiles,
  },
  {
    name: "Source metadata",
    category: "semantics",
    route: "/components/source-metadata",
    search: ["semantics", "source", "retrieval"],
    profiles: sharedProfiles,
  },
  {
    name: "Provenance",
    category: "semantics",
    route: "/components/provenance",
    search: ["semantics", "origin", "method"],
    profiles: sharedProfiles,
  },
  {
    name: "Epistemic label",
    category: "semantics",
    route: "/components/epistemic-label",
    search: ["semantics", "fact", "machine", "human"],
    profiles: sharedProfiles,
  },
  {
    name: "Financial value",
    category: "semantics",
    route: "/components/financial-value",
    search: ["semantics", "finance", "basis", "period"],
    profiles: sharedProfiles,
  },
  {
    name: "Market direction",
    category: "semantics",
    route: "/components/market-direction",
    search: ["semantics", "market", "up", "down", "flat"],
    profiles: sharedProfiles,
  },
  {
    name: "Freshness label",
    category: "semantics",
    route: "/components/freshness-label",
    search: ["semantics", "current", "delayed", "stale"],
    profiles: sharedProfiles,
  },
  {
    name: "Pythia signal",
    category: "semantics",
    route: "/components/pythia-signal",
    search: ["semantics", "analysis", "signal"],
    profiles: sharedProfiles,
  },
  {
    name: "Semantic message",
    category: "semantics",
    route: "/components/semantic-message",
    search: ["semantics", "information", "warning", "error"],
    profiles: sharedProfiles,
  },
  {
    name: "Knowledge state",
    category: "semantics",
    route: "/components/knowledge-state",
    search: ["semantics", "unknown", "incomplete", "unavailable"],
    profiles: sharedProfiles,
  },
] as const satisfies readonly CatalogEntry[];

export const catalogEntryByRoute = new Map(
  componentCatalog.map((entry) => [entry.route, entry]),
);
