import { catalogProfiles, type CatalogEntry } from "./catalog-schema";

const sharedProfiles = catalogProfiles;

export const primaryCatalog = [
  {
    name: "Button",
    category: "actions",
    route: "/components/button",
    search: ["action", "loading", "primary"],
    profiles: sharedProfiles,
  },
  {
    name: "Icon button",
    category: "actions",
    route: "/components/icon-button",
    search: ["action", "icon", "label"],
    profiles: sharedProfiles,
  },
  {
    name: "Button group",
    category: "actions",
    route: "/components/button-group",
    search: ["actions", "group"],
    profiles: sharedProfiles,
  },
  {
    name: "Link button",
    category: "actions",
    route: "/components/link-button",
    search: ["action", "anchor", "link"],
    profiles: sharedProfiles,
  },
  {
    name: "Toggle",
    category: "actions",
    route: "/components/toggle",
    search: ["action", "pressed"],
    profiles: sharedProfiles,
  },
  {
    name: "Toggle group",
    category: "actions",
    route: "/components/toggle-group",
    search: ["actions", "pressed", "group"],
    profiles: sharedProfiles,
  },
  {
    name: "Input",
    category: "forms",
    route: "/components/input",
    search: ["form", "text", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Textarea",
    category: "forms",
    route: "/components/textarea",
    search: ["form", "multiline", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Label",
    category: "forms",
    route: "/components/label",
    search: ["form", "accessible", "control"],
    profiles: sharedProfiles,
  },
  {
    name: "Field",
    category: "forms",
    route: "/components/field",
    search: ["form", "description", "error"],
    profiles: sharedProfiles,
  },
  {
    name: "Input group",
    category: "forms",
    route: "/components/input-group",
    search: ["form", "prefix", "suffix"],
    profiles: sharedProfiles,
  },
  {
    name: "OTP field",
    category: "forms",
    route: "/components/otp-field",
    search: ["form", "one-time password", "code"],
    profiles: sharedProfiles,
  },
  {
    name: "Calendar",
    category: "calendar",
    route: "/components/calendar",
    search: ["date", "day picker"],
    profiles: sharedProfiles,
  },
  {
    name: "Date picker",
    category: "calendar",
    route: "/components/date-picker",
    search: ["calendar", "date", "popover"],
    profiles: sharedProfiles,
  },
  {
    name: "Checkbox",
    category: "selection",
    route: "/components/checkbox",
    search: ["selection", "checked", "indeterminate"],
    profiles: sharedProfiles,
  },
  {
    name: "Radio group",
    category: "selection",
    route: "/components/radio-group",
    search: ["selection", "single choice", "radio"],
    profiles: sharedProfiles,
  },
  {
    name: "Switch",
    category: "selection",
    route: "/components/switch",
    search: ["selection", "toggle", "checked"],
    profiles: sharedProfiles,
  },
  {
    name: "Select",
    category: "selection",
    route: "/components/select",
    search: ["selection", "listbox", "options"],
    profiles: sharedProfiles,
  },
  {
    name: "Combobox",
    category: "selection",
    route: "/components/combobox",
    search: ["selection", "autocomplete", "filter"],
    profiles: sharedProfiles,
  },
  {
    name: "Command",
    category: "selection",
    route: "/components/command",
    search: ["selection", "palette", "search"],
    profiles: sharedProfiles,
  },
  {
    name: "Tabs",
    category: "navigation",
    route: "/components/tabs",
    search: ["navigation", "panels"],
    profiles: sharedProfiles,
  },
  {
    name: "Breadcrumb",
    category: "navigation",
    route: "/components/breadcrumb",
    search: ["navigation", "hierarchy", "trail"],
    profiles: sharedProfiles,
  },
  {
    name: "Pagination",
    category: "navigation",
    route: "/components/pagination",
    search: ["navigation", "pages"],
    profiles: sharedProfiles,
  },
  {
    name: "Navigation menu",
    category: "navigation",
    route: "/components/navigation-menu",
    search: ["navigation", "menu", "links"],
    profiles: sharedProfiles,
  },
  {
    name: "Sidebar",
    category: "navigation",
    route: "/components/sidebar",
    search: ["navigation", "rail", "sections"],
    profiles: sharedProfiles,
  },
  {
    name: "Dialog",
    category: "overlays",
    route: "/components/dialog",
    search: ["overlay", "modal"],
    profiles: sharedProfiles,
  },
  {
    name: "Alert dialog",
    category: "overlays",
    route: "/components/alert-dialog",
    search: ["overlay", "confirmation", "modal"],
    profiles: sharedProfiles,
  },
  {
    name: "Drawer / sheet",
    category: "overlays",
    route: "/components/drawer-sheet",
    search: ["overlay", "drawer", "sheet"],
    profiles: sharedProfiles,
  },
  {
    name: "Popover",
    category: "overlays",
    route: "/components/popover",
    search: ["overlay", "floating"],
    profiles: sharedProfiles,
  },
  {
    name: "Tooltip",
    category: "overlays",
    route: "/components/tooltip",
    search: ["overlay", "hint"],
    profiles: sharedProfiles,
  },
  {
    name: "Preview / hover card",
    category: "overlays",
    route: "/components/preview-hover-card",
    search: ["overlay", "preview", "hover card"],
    profiles: sharedProfiles,
  },
  {
    name: "Dropdown / menu",
    category: "overlays",
    route: "/components/dropdown-menu",
    search: ["overlay", "dropdown", "menu"],
    profiles: sharedProfiles,
  },
  {
    name: "Context menu",
    category: "overlays",
    route: "/components/context-menu",
    search: ["overlay", "menu", "right click"],
    profiles: sharedProfiles,
  },
] as const satisfies readonly CatalogEntry[];
