import { catalogProfiles, type CatalogEntry } from "./catalog-schema";

const sharedProfiles = catalogProfiles;

export const secondaryCatalog = [
  {
    name: "Accordion",
    category: "disclosure",
    route: "/components/accordion",
    search: ["disclosure", "expand", "collapse"],
    profiles: sharedProfiles,
  },
  {
    name: "Collapsible",
    category: "disclosure",
    route: "/components/collapsible",
    search: ["disclosure", "expand", "collapse"],
    profiles: sharedProfiles,
  },
  {
    name: "Details",
    category: "disclosure",
    route: "/components/details",
    search: ["disclosure", "native", "summary"],
    profiles: sharedProfiles,
  },
  {
    name: "Alert",
    category: "feedback",
    route: "/components/alert",
    search: ["feedback", "status", "message"],
    profiles: sharedProfiles,
  },
  {
    name: "Badge",
    category: "feedback",
    route: "/components/badge",
    search: ["feedback", "status", "label"],
    profiles: sharedProfiles,
  },
  {
    name: "Progress",
    category: "feedback",
    route: "/components/progress",
    search: ["feedback", "percentage", "determinate"],
    profiles: sharedProfiles,
  },
  {
    name: "Skeleton",
    category: "feedback",
    route: "/components/skeleton",
    search: ["feedback", "loading", "placeholder"],
    profiles: sharedProfiles,
  },
  {
    name: "Activity indicator",
    category: "feedback",
    route: "/components/activity-indicator",
    search: ["feedback", "loading", "indeterminate"],
    profiles: sharedProfiles,
  },
  {
    name: "Toast",
    category: "feedback",
    route: "/components/toast",
    search: ["feedback", "notification", "queue"],
    profiles: sharedProfiles,
  },
  {
    name: "Card",
    category: "data-display",
    route: "/components/card",
    search: ["data display", "surface", "container"],
    profiles: sharedProfiles,
  },
  {
    name: "Table",
    category: "data-display",
    route: "/components/table",
    search: ["data display", "rows", "columns"],
    profiles: sharedProfiles,
  },
  {
    name: "Avatar",
    category: "data-display",
    route: "/components/avatar",
    search: ["data display", "image", "fallback"],
    profiles: sharedProfiles,
  },
  {
    name: "Scroll area",
    category: "data-display",
    route: "/components/scroll-area",
    search: ["data display", "scrollbar", "overflow"],
    profiles: sharedProfiles,
  },
  {
    name: "Separator",
    category: "data-display",
    route: "/components/separator",
    search: ["data display", "divider"],
    profiles: sharedProfiles,
  },
  {
    name: "Empty state",
    category: "data-display",
    route: "/components/empty-state",
    search: ["data display", "empty", "no results"],
    profiles: sharedProfiles,
  },
  {
    name: "Container",
    category: "layout",
    route: "/components/container",
    search: ["layout", "measure", "width"],
    profiles: sharedProfiles,
  },
  {
    name: "Stack",
    category: "layout",
    route: "/components/stack",
    search: ["layout", "vertical", "gap"],
    profiles: sharedProfiles,
  },
  {
    name: "Inline",
    category: "layout",
    route: "/components/inline",
    search: ["layout", "horizontal", "gap"],
    profiles: sharedProfiles,
  },
  {
    name: "Resizable panels",
    category: "layout",
    route: "/components/resizable-panels",
    search: ["layout", "panels", "resize"],
    profiles: sharedProfiles,
  },
  {
    name: "Citation",
    category: "semantics",
    route: "/components/citation",
    search: ["semantics", "source", "citation"],
    profiles: sharedProfiles,
  },
  {
    name: "Source metadata",
    category: "semantics",
    route: "/components/source-metadata",
    search: ["semantics", "source", "retrieval"],
    profiles: sharedProfiles,
  },
  {
    name: "Provenance",
    category: "semantics",
    route: "/components/provenance",
    search: ["semantics", "origin", "method"],
    profiles: sharedProfiles,
  },
  {
    name: "Epistemic label",
    category: "semantics",
    route: "/components/epistemic-label",
    search: ["semantics", "fact", "machine", "human"],
    profiles: sharedProfiles,
  },
  {
    name: "Financial value",
    category: "semantics",
    route: "/components/financial-value",
    search: ["semantics", "finance", "basis", "period"],
    profiles: sharedProfiles,
  },
  {
    name: "Market direction",
    category: "semantics",
    route: "/components/market-direction",
    search: ["semantics", "market", "up", "down", "flat"],
    profiles: sharedProfiles,
  },
  {
    name: "Freshness label",
    category: "semantics",
    route: "/components/freshness-label",
    search: ["semantics", "current", "delayed", "stale"],
    profiles: sharedProfiles,
  },
  {
    name: "Pythia signal",
    category: "semantics",
    route: "/components/pythia-signal",
    search: ["semantics", "analysis", "signal"],
    profiles: sharedProfiles,
  },
  {
    name: "Semantic message",
    category: "semantics",
    route: "/components/semantic-message",
    search: ["semantics", "information", "warning", "error"],
    profiles: sharedProfiles,
  },
  {
    name: "Knowledge state",
    category: "semantics",
    route: "/components/knowledge-state",
    search: ["semantics", "unknown", "incomplete", "unavailable"],
    profiles: sharedProfiles,
  },
] as const satisfies readonly CatalogEntry[];
